[providers]
providers = ['php', 'node']

[variables]
APP_URL = 'http://localhost'
APP_KEY = 'base64:sxShQ7aMj5IxdBkPuF7OYU7kwe2XFqIoAyz5eo7f6ko='

[phases.setup]
nixPkgs = [
  'php82',
  'php82Packages.composer',
  'php82Extensions.pdo_mysql',
  'php82Extensions.mbstring',
  'php82Extensions.tokenizer',
  'php82Extensions.xml',
  'php82Extensions.curl',
  'nodejs_20'
]

[phases.build]
cmds = [
  'composer install --optimize-autoloader --no-dev --no-scripts',
  'npm install',
  'npm run build',
  'chmod -R 777 storage bootstrap/cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'
